package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8Cluster;

public interface Ku8ClusterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_cluster
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_cluster",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_cluster
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_cluster (ID, TENANT_ID, ",
        "ZONE_ID, NAME, LABELS, ",
        "K8S_VERSION, INSTALL_TYPE, ",
        "NOTE, LAST_UPDATED)",
        "values (#{id,jdbcType=INTEGER}, #{tenantId,jdbcType=INTEGER}, ",
        "#{zoneId,jdbcType=INTEGER}, #{name,jdbcType=CHAR}, #{labels,jdbcType=VARCHAR}, ",
        "#{k8sVersion,jdbcType=CHAR}, #{installType,jdbcType=TINYINT}, ",
        "#{note,jdbcType=VARCHAR}, #{lastUpdated,jdbcType=TIMESTAMP})"
    })
    int insert(Ku8Cluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_cluster
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, ZONE_ID, NAME, LABELS, K8S_VERSION, INSTALL_TYPE, NOTE, LAST_UPDATED",
        "from ku8_cluster",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAME", property="name", jdbcType=JdbcType.CHAR),
        @Result(column="LABELS", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="K8S_VERSION", property="k8sVersion", jdbcType=JdbcType.CHAR),
        @Result(column="INSTALL_TYPE", property="installType", jdbcType=JdbcType.TINYINT),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    Ku8Cluster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_cluster
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, ZONE_ID, NAME, LABELS, K8S_VERSION, INSTALL_TYPE, LAST_UPDATED",
        "from ku8_cluster"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAME", property="name", jdbcType=JdbcType.CHAR),
        @Result(column="LABELS", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="K8S_VERSION", property="k8sVersion", jdbcType=JdbcType.CHAR),
        @Result(column="INSTALL_TYPE", property="installType", jdbcType=JdbcType.TINYINT),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Ku8Cluster> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_cluster
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_cluster",
        "set TENANT_ID = #{tenantId,jdbcType=INTEGER},",
          "ZONE_ID = #{zoneId,jdbcType=INTEGER},",
          "NAME = #{name,jdbcType=CHAR},",
          "LABELS = #{labels,jdbcType=VARCHAR},",
          "K8S_VERSION = #{k8sVersion,jdbcType=CHAR},",
          "INSTALL_TYPE = #{installType,jdbcType=TINYINT},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8Cluster record);
}