package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8Group;

public interface Ku8GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_group
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_group",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_group
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_group (ID, TENANT_ID, ",
        "CLUSTER_ID, NAME, LABEL, ",
        "NOTE, LAST_UPDATED)",
        "values (#{id,jdbcType=INTEGER}, #{tenantId,jdbcType=INTEGER}, ",
        "#{clusterId,jdbcType=INTEGER}, #{name,jdbcType=CHAR}, #{label,jdbcType=VARCHAR}, ",
        "#{note,jdbcType=VARCHAR}, #{lastUpdated,jdbcType=TIMESTAMP})"
    })
    int insert(Ku8Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_group
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, CLUSTER_ID, NAME, LABEL, NOTE, LAST_UPDATED",
        "from ku8_group",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAME", property="name", jdbcType=JdbcType.CHAR),
        @Result(column="LABEL", property="label", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    Ku8Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_group
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, CLUSTER_ID, NAME, LABEL, NOTE, LAST_UPDATED",
        "from ku8_group"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAME", property="name", jdbcType=JdbcType.CHAR),
        @Result(column="LABEL", property="label", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Ku8Group> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_group
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_group",
        "set TENANT_ID = #{tenantId,jdbcType=INTEGER},",
          "CLUSTER_ID = #{clusterId,jdbcType=INTEGER},",
          "NAME = #{name,jdbcType=CHAR},",
          "LABEL = #{label,jdbcType=VARCHAR},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8Group record);
}