package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8ProjRcInst;

public interface Ku8ProjRcInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_rc_inst
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_proj_rc_inst",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_rc_inst
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_proj_rc_inst (ID, PROJECTID, ",
        "PROJECT_INSTANCE_ID, PROJECT_SERVICE_ID, ",
        "TENANT_ID, ZONE_ID, ",
        "NAMESPACE, RC_NAME, ",
        "POD_LABEL, NOTE, ",
        "LAST_UPDATED)",
        "values (#{id,jdbcType=INTEGER}, #{projectid,jdbcType=INTEGER}, ",
        "#{projectInstanceId,jdbcType=INTEGER}, #{projectServiceId,jdbcType=INTEGER}, ",
        "#{tenantId,jdbcType=INTEGER}, #{zoneId,jdbcType=INTEGER}, ",
        "#{namespace,jdbcType=CHAR}, #{rcName,jdbcType=VARCHAR}, ",
        "#{podLabel,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR}, ",
        "#{lastUpdated,jdbcType=TIMESTAMP})"
    })
    int insert(Ku8ProjRcInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_rc_inst
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, PROJECTID, PROJECT_INSTANCE_ID, PROJECT_SERVICE_ID, TENANT_ID, ZONE_ID, ",
        "NAMESPACE, RC_NAME, POD_LABEL, NOTE, LAST_UPDATED",
        "from ku8_proj_rc_inst",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PROJECTID", property="projectid", jdbcType=JdbcType.INTEGER),
        @Result(column="PROJECT_INSTANCE_ID", property="projectInstanceId", jdbcType=JdbcType.INTEGER),
        @Result(column="PROJECT_SERVICE_ID", property="projectServiceId", jdbcType=JdbcType.INTEGER),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR),
        @Result(column="RC_NAME", property="rcName", jdbcType=JdbcType.VARCHAR),
        @Result(column="POD_LABEL", property="podLabel", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    Ku8ProjRcInst selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_rc_inst
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, PROJECTID, PROJECT_INSTANCE_ID, PROJECT_SERVICE_ID, TENANT_ID, ZONE_ID, ",
        "NAMESPACE, RC_NAME, POD_LABEL, NOTE, LAST_UPDATED",
        "from ku8_proj_rc_inst"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PROJECTID", property="projectid", jdbcType=JdbcType.INTEGER),
        @Result(column="PROJECT_INSTANCE_ID", property="projectInstanceId", jdbcType=JdbcType.INTEGER),
        @Result(column="PROJECT_SERVICE_ID", property="projectServiceId", jdbcType=JdbcType.INTEGER),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR),
        @Result(column="RC_NAME", property="rcName", jdbcType=JdbcType.VARCHAR),
        @Result(column="POD_LABEL", property="podLabel", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Ku8ProjRcInst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_rc_inst
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_proj_rc_inst",
        "set PROJECTID = #{projectid,jdbcType=INTEGER},",
          "PROJECT_INSTANCE_ID = #{projectInstanceId,jdbcType=INTEGER},",
          "PROJECT_SERVICE_ID = #{projectServiceId,jdbcType=INTEGER},",
          "TENANT_ID = #{tenantId,jdbcType=INTEGER},",
          "ZONE_ID = #{zoneId,jdbcType=INTEGER},",
          "NAMESPACE = #{namespace,jdbcType=CHAR},",
          "RC_NAME = #{rcName,jdbcType=VARCHAR},",
          "POD_LABEL = #{podLabel,jdbcType=VARCHAR},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8ProjRcInst record);
}