package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8ProjInstance;

public interface Ku8ProjInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_instance
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_proj_instance",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_instance
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_proj_instance (ID, PROJECTID, ",
        "TENANT_ID, ZONE_ID, ",
        "CLUSTER_ID, KU8_GROUP_ID, ",
        "NAMESPACE, STATUS, ",
        "NOTE, LAST_UPDATED)",
        "values (#{id,jdbcType=INTEGER}, #{projectid,jdbcType=INTEGER}, ",
        "#{tenantId,jdbcType=INTEGER}, #{zoneId,jdbcType=INTEGER}, ",
        "#{clusterId,jdbcType=INTEGER}, #{ku8GroupId,jdbcType=INTEGER}, ",
        "#{namespace,jdbcType=CHAR}, #{status,jdbcType=TINYINT}, ",
        "#{note,jdbcType=VARCHAR}, #{lastUpdated,jdbcType=TIMESTAMP})"
    })
    int insert(Ku8ProjInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_instance
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, PROJECTID, TENANT_ID, ZONE_ID, CLUSTER_ID, KU8_GROUP_ID, NAMESPACE, STATUS, ",
        "NOTE, LAST_UPDATED",
        "from ku8_proj_instance",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PROJECTID", property="projectid", jdbcType=JdbcType.INTEGER),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="KU8_GROUP_ID", property="ku8GroupId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    Ku8ProjInstance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_instance
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, PROJECTID, TENANT_ID, ZONE_ID, CLUSTER_ID, KU8_GROUP_ID, NAMESPACE, STATUS, ",
        "NOTE, LAST_UPDATED",
        "from ku8_proj_instance"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="PROJECTID", property="projectid", jdbcType=JdbcType.INTEGER),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="KU8_GROUP_ID", property="ku8GroupId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Ku8ProjInstance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_proj_instance
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_proj_instance",
        "set PROJECTID = #{projectid,jdbcType=INTEGER},",
          "TENANT_ID = #{tenantId,jdbcType=INTEGER},",
          "ZONE_ID = #{zoneId,jdbcType=INTEGER},",
          "CLUSTER_ID = #{clusterId,jdbcType=INTEGER},",
          "KU8_GROUP_ID = #{ku8GroupId,jdbcType=INTEGER},",
          "NAMESPACE = #{namespace,jdbcType=CHAR},",
          "STATUS = #{status,jdbcType=TINYINT},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8ProjInstance record);
}