package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8Project;

public interface Ku8ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_project",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_project (ID, TENANT_ID, ",
        "OWNER, NAME, VERSION, ",
        "K8S_VERSION, NOTE, LAST_UPDATED, ",
        "YAML_SPEC)",
        "values (#{id,jdbcType=INTEGER}, #{tenantId,jdbcType=INTEGER}, ",
        "#{owner,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{version,jdbcType=CHAR}, ",
        "#{k8sVersion,jdbcType=CHAR}, #{note,jdbcType=VARCHAR}, #{lastUpdated,jdbcType=TIMESTAMP}, ",
        "#{yamlSpec,jdbcType=LONGVARCHAR})"
    })
    int insert(Ku8Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME, VERSION, K8S_VERSION, NOTE, LAST_UPDATED, YAML_SPEC",
        "from ku8_project",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.CHAR),
        @Result(column="K8S_VERSION", property="k8sVersion", jdbcType=JdbcType.CHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="YAML_SPEC", property="yamlSpec", jdbcType=JdbcType.LONGVARCHAR)
    })
    Ku8Project selectByPrimaryKey(Integer id);

    /**
     * modified ,only select usefull project
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME",
        "from ku8_project"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
    })
    List<Ku8Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_project",
        "set TENANT_ID = #{tenantId,jdbcType=INTEGER},",
          "OWNER = #{owner,jdbcType=CHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "VERSION = #{version,jdbcType=CHAR},",
          "K8S_VERSION = #{k8sVersion,jdbcType=CHAR},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP},",
          "YAML_SPEC = #{yamlSpec,jdbcType=LONGVARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8Project record);
}