package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8ResPartion;

public interface Ku8ResPartionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_res_partion
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_res_partion",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_res_partion
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_res_partion (ID, CLUSTER_ID, ",
        "NAMESPACE, NOTE, LAST_UPDATED)",
        "values (#{id,jdbcType=INTEGER}, #{clusterId,jdbcType=INTEGER}, ",
        "#{namespace,jdbcType=CHAR}, #{note,jdbcType=VARCHAR}, #{lastUpdated,jdbcType=TIMESTAMP})"
    })
    int insert(Ku8ResPartion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_res_partion
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, CLUSTER_ID, NAMESPACE, NOTE, LAST_UPDATED",
        "from ku8_res_partion",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    Ku8ResPartion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_res_partion
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, CLUSTER_ID, NAMESPACE, NOTE, LAST_UPDATED",
        "from ku8_res_partion"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Ku8ResPartion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_res_partion
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_res_partion",
        "set CLUSTER_ID = #{clusterId,jdbcType=INTEGER},",
          "NAMESPACE = #{namespace,jdbcType=CHAR},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8ResPartion record);
}