package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8ServiceTemplate;

public interface Ku8ServiceTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_service_template
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_service_template",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_service_template
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_service_template (ID, TENANT_ID, ",
        "OWNER, NAME, ICON_URL, ",
        "VERSION, K8S_VERSION, ZONE_ID, ",
        "CLUSTER_ID, JSON_SPEC, ",
        "PREV_JSON_SPEC, NOTE, ",
        "LAST_UPDATED)",
        "values (#{id,jdbcType=INTEGER}, #{tenantId,jdbcType=INTEGER}, ",
        "#{owner,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{iconUrl,jdbcType=VARCHAR}, ",
        "#{version,jdbcType=CHAR}, #{k8sVersion,jdbcType=CHAR}, #{zoneId,jdbcType=INTEGER}, ",
        "#{clusterId,jdbcType=INTEGER}, #{jsonSpec,jdbcType=VARCHAR}, ",
        "#{prevJsonSpec,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR}, ",
        "#{lastUpdated,jdbcType=TIMESTAMP})"
    })
    int insert(Ku8ServiceTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_service_template
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME, ICON_URL, VERSION, K8S_VERSION, ZONE_ID, CLUSTER_ID, ",
        "JSON_SPEC, PREV_JSON_SPEC, NOTE, LAST_UPDATED",
        "from ku8_service_template",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICON_URL", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.CHAR),
        @Result(column="K8S_VERSION", property="k8sVersion", jdbcType=JdbcType.CHAR),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="JSON_SPEC", property="jsonSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_JSON_SPEC", property="prevJsonSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    Ku8ServiceTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_service_template
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME, ICON_URL, VERSION, K8S_VERSION, ZONE_ID, CLUSTER_ID, ",
        "JSON_SPEC, PREV_JSON_SPEC, NOTE, LAST_UPDATED",
        "from ku8_service_template"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICON_URL", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.CHAR),
        @Result(column="K8S_VERSION", property="k8sVersion", jdbcType=JdbcType.CHAR),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="JSON_SPEC", property="jsonSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_JSON_SPEC", property="prevJsonSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Ku8ServiceTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_service_template
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_service_template",
        "set TENANT_ID = #{tenantId,jdbcType=INTEGER},",
          "OWNER = #{owner,jdbcType=CHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "ICON_URL = #{iconUrl,jdbcType=VARCHAR},",
          "VERSION = #{version,jdbcType=CHAR},",
          "K8S_VERSION = #{k8sVersion,jdbcType=CHAR},",
          "ZONE_ID = #{zoneId,jdbcType=INTEGER},",
          "CLUSTER_ID = #{clusterId,jdbcType=INTEGER},",
          "JSON_SPEC = #{jsonSpec,jdbcType=VARCHAR},",
          "PREV_JSON_SPEC = #{prevJsonSpec,jdbcType=VARCHAR},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8ServiceTemplate record);
}