package org.ku8eye.domain;

import java.util.Date;

public class Host {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.ZONE_ID
     *
     * @mbggenerated
     */
    private Integer zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.HOST_NAME
     *
     * @mbggenerated
     */
    private String hostName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.IP
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.ROOT_PASSWD
     *
     * @mbggenerated
     */
    private String rootPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.LOCATION
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.CORES
     *
     * @mbggenerated
     */
    private Short cores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.MEMORY
     *
     * @mbggenerated
     */
    private Integer memory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.USAGE_FLAG
     *
     * @mbggenerated
     */
    private Byte usageFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.SSH_LOGIN
     *
     * @mbggenerated
     */
    private Byte sshLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.ID
     *
     * @return the value of host.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.ID
     *
     * @param id the value for host.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.ZONE_ID
     *
     * @return the value of host.ZONE_ID
     *
     * @mbggenerated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.ZONE_ID
     *
     * @param zoneId the value for host.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.HOST_NAME
     *
     * @return the value of host.HOST_NAME
     *
     * @mbggenerated
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.HOST_NAME
     *
     * @param hostName the value for host.HOST_NAME
     *
     * @mbggenerated
     */
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.IP
     *
     * @return the value of host.IP
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.IP
     *
     * @param ip the value for host.IP
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.ROOT_PASSWD
     *
     * @return the value of host.ROOT_PASSWD
     *
     * @mbggenerated
     */
    public String getRootPasswd() {
        return rootPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.ROOT_PASSWD
     *
     * @param rootPasswd the value for host.ROOT_PASSWD
     *
     * @mbggenerated
     */
    public void setRootPasswd(String rootPasswd) {
        this.rootPasswd = rootPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.LOCATION
     *
     * @return the value of host.LOCATION
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.LOCATION
     *
     * @param location the value for host.LOCATION
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.NOTE
     *
     * @return the value of host.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.NOTE
     *
     * @param note the value for host.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.LAST_UPDATED
     *
     * @return the value of host.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.LAST_UPDATED
     *
     * @param lastUpdated the value for host.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.CORES
     *
     * @return the value of host.CORES
     *
     * @mbggenerated
     */
    public Short getCores() {
        return cores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.CORES
     *
     * @param cores the value for host.CORES
     *
     * @mbggenerated
     */
    public void setCores(Short cores) {
        this.cores = cores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.MEMORY
     *
     * @return the value of host.MEMORY
     *
     * @mbggenerated
     */
    public Integer getMemory() {
        return memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.MEMORY
     *
     * @param memory the value for host.MEMORY
     *
     * @mbggenerated
     */
    public void setMemory(Integer memory) {
        this.memory = memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.USAGE_FLAG
     *
     * @return the value of host.USAGE_FLAG
     *
     * @mbggenerated
     */
    public Byte getUsageFlag() {
        return usageFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.USAGE_FLAG
     *
     * @param usageFlag the value for host.USAGE_FLAG
     *
     * @mbggenerated
     */
    public void setUsageFlag(Byte usageFlag) {
        this.usageFlag = usageFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.SSH_LOGIN
     *
     * @return the value of host.SSH_LOGIN
     *
     * @mbggenerated
     */
    public Byte getSshLogin() {
        return sshLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.SSH_LOGIN
     *
     * @param sshLogin the value for host.SSH_LOGIN
     *
     * @mbggenerated
     */
    public void setSshLogin(Byte sshLogin) {
        this.sshLogin = sshLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.CLUSTER_ID
     *
     * @return the value of host.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.CLUSTER_ID
     *
     * @param clusterId the value for host.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }
}