package org.ku8eye.domain;

import java.util.Date;

public class Ku8Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.TENANT_ID
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.OWNER
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.K8S_VERSION
     *
     * @mbggenerated
     */
    private String k8sVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_project.YAML_SPEC
     *
     * @mbggenerated
     */
    private String yamlSpec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.ID
     *
     * @return the value of ku8_project.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.ID
     *
     * @param id the value for ku8_project.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.TENANT_ID
     *
     * @return the value of ku8_project.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.TENANT_ID
     *
     * @param tenantId the value for ku8_project.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.OWNER
     *
     * @return the value of ku8_project.OWNER
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.OWNER
     *
     * @param owner the value for ku8_project.OWNER
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.NAME
     *
     * @return the value of ku8_project.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.NAME
     *
     * @param name the value for ku8_project.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.VERSION
     *
     * @return the value of ku8_project.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.VERSION
     *
     * @param version the value for ku8_project.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.K8S_VERSION
     *
     * @return the value of ku8_project.K8S_VERSION
     *
     * @mbggenerated
     */
    public String getK8sVersion() {
        return k8sVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.K8S_VERSION
     *
     * @param k8sVersion the value for ku8_project.K8S_VERSION
     *
     * @mbggenerated
     */
    public void setK8sVersion(String k8sVersion) {
        this.k8sVersion = k8sVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.NOTE
     *
     * @return the value of ku8_project.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.NOTE
     *
     * @param note the value for ku8_project.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.LAST_UPDATED
     *
     * @return the value of ku8_project.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_project.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_project.YAML_SPEC
     *
     * @return the value of ku8_project.YAML_SPEC
     *
     * @mbggenerated
     */
    public String getYamlSpec() {
        return yamlSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_project.YAML_SPEC
     *
     * @param yamlSpec the value for ku8_project.YAML_SPEC
     *
     * @mbggenerated
     */
    public void setYamlSpec(String yamlSpec) {
        this.yamlSpec = yamlSpec;
    }
}