package org.ku8eye.domain;

import java.util.Date;

public class Ku8ProjServiceInst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.PROJECTID
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    private Integer projectInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.TENANT_ID
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.ZONE_ID
     *
     * @mbggenerated
     */
    private Integer zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.KU8_GROUP_ID
     *
     * @mbggenerated
     */
    private Integer ku8GroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.NAMESPACE
     *
     * @mbggenerated
     */
    private String namespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.SERVICE_NAME
     *
     * @mbggenerated
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.REPLICA
     *
     * @mbggenerated
     */
    private Byte replica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_service_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.ID
     *
     * @return the value of ku8_proj_service_inst.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.ID
     *
     * @param id the value for ku8_proj_service_inst.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.PROJECTID
     *
     * @return the value of ku8_proj_service_inst.PROJECTID
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.PROJECTID
     *
     * @param projectid the value for ku8_proj_service_inst.PROJECTID
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.PROJECT_INSTANCE_ID
     *
     * @return the value of ku8_proj_service_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    public Integer getProjectInstanceId() {
        return projectInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.PROJECT_INSTANCE_ID
     *
     * @param projectInstanceId the value for ku8_proj_service_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    public void setProjectInstanceId(Integer projectInstanceId) {
        this.projectInstanceId = projectInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.TENANT_ID
     *
     * @return the value of ku8_proj_service_inst.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.TENANT_ID
     *
     * @param tenantId the value for ku8_proj_service_inst.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.ZONE_ID
     *
     * @return the value of ku8_proj_service_inst.ZONE_ID
     *
     * @mbggenerated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.ZONE_ID
     *
     * @param zoneId the value for ku8_proj_service_inst.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.CLUSTER_ID
     *
     * @return the value of ku8_proj_service_inst.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.CLUSTER_ID
     *
     * @param clusterId the value for ku8_proj_service_inst.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.KU8_GROUP_ID
     *
     * @return the value of ku8_proj_service_inst.KU8_GROUP_ID
     *
     * @mbggenerated
     */
    public Integer getKu8GroupId() {
        return ku8GroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.KU8_GROUP_ID
     *
     * @param ku8GroupId the value for ku8_proj_service_inst.KU8_GROUP_ID
     *
     * @mbggenerated
     */
    public void setKu8GroupId(Integer ku8GroupId) {
        this.ku8GroupId = ku8GroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.NAMESPACE
     *
     * @return the value of ku8_proj_service_inst.NAMESPACE
     *
     * @mbggenerated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.NAMESPACE
     *
     * @param namespace the value for ku8_proj_service_inst.NAMESPACE
     *
     * @mbggenerated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.SERVICE_NAME
     *
     * @return the value of ku8_proj_service_inst.SERVICE_NAME
     *
     * @mbggenerated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.SERVICE_NAME
     *
     * @param serviceName the value for ku8_proj_service_inst.SERVICE_NAME
     *
     * @mbggenerated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.REPLICA
     *
     * @return the value of ku8_proj_service_inst.REPLICA
     *
     * @mbggenerated
     */
    public Byte getReplica() {
        return replica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.REPLICA
     *
     * @param replica the value for ku8_proj_service_inst.REPLICA
     *
     * @mbggenerated
     */
    public void setReplica(Byte replica) {
        this.replica = replica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.NOTE
     *
     * @return the value of ku8_proj_service_inst.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.NOTE
     *
     * @param note the value for ku8_proj_service_inst.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_service_inst.LAST_UPDATED
     *
     * @return the value of ku8_proj_service_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_service_inst.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_proj_service_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}