package org.ku8eye.domain;

import java.util.Date;

public class Ku8ProjInstance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.PROJECTID
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.TENANT_ID
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.ZONE_ID
     *
     * @mbggenerated
     */
    private Integer zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.KU8_GROUP_ID
     *
     * @mbggenerated
     */
    private Integer ku8GroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.NAMESPACE
     *
     * @mbggenerated
     */
    private String namespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.STATUS
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_instance.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.ID
     *
     * @return the value of ku8_proj_instance.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.ID
     *
     * @param id the value for ku8_proj_instance.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.PROJECTID
     *
     * @return the value of ku8_proj_instance.PROJECTID
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.PROJECTID
     *
     * @param projectid the value for ku8_proj_instance.PROJECTID
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.TENANT_ID
     *
     * @return the value of ku8_proj_instance.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.TENANT_ID
     *
     * @param tenantId the value for ku8_proj_instance.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.ZONE_ID
     *
     * @return the value of ku8_proj_instance.ZONE_ID
     *
     * @mbggenerated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.ZONE_ID
     *
     * @param zoneId the value for ku8_proj_instance.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.CLUSTER_ID
     *
     * @return the value of ku8_proj_instance.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.CLUSTER_ID
     *
     * @param clusterId the value for ku8_proj_instance.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.KU8_GROUP_ID
     *
     * @return the value of ku8_proj_instance.KU8_GROUP_ID
     *
     * @mbggenerated
     */
    public Integer getKu8GroupId() {
        return ku8GroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.KU8_GROUP_ID
     *
     * @param ku8GroupId the value for ku8_proj_instance.KU8_GROUP_ID
     *
     * @mbggenerated
     */
    public void setKu8GroupId(Integer ku8GroupId) {
        this.ku8GroupId = ku8GroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.NAMESPACE
     *
     * @return the value of ku8_proj_instance.NAMESPACE
     *
     * @mbggenerated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.NAMESPACE
     *
     * @param namespace the value for ku8_proj_instance.NAMESPACE
     *
     * @mbggenerated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.STATUS
     *
     * @return the value of ku8_proj_instance.STATUS
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.STATUS
     *
     * @param status the value for ku8_proj_instance.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.NOTE
     *
     * @return the value of ku8_proj_instance.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.NOTE
     *
     * @param note the value for ku8_proj_instance.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_instance.LAST_UPDATED
     *
     * @return the value of ku8_proj_instance.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_instance.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_proj_instance.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}