package org.ku8eye.domain;

import java.util.Date;

public class Ku8ProjRcInst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.PROJECTID
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    private Integer projectInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.PROJECT_SERVICE_ID
     *
     * @mbggenerated
     */
    private Integer projectServiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.TENANT_ID
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.ZONE_ID
     *
     * @mbggenerated
     */
    private Integer zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.NAMESPACE
     *
     * @mbggenerated
     */
    private String namespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.RC_NAME
     *
     * @mbggenerated
     */
    private String rcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.POD_LABEL
     *
     * @mbggenerated
     */
    private String podLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_proj_rc_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.ID
     *
     * @return the value of ku8_proj_rc_inst.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.ID
     *
     * @param id the value for ku8_proj_rc_inst.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.PROJECTID
     *
     * @return the value of ku8_proj_rc_inst.PROJECTID
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.PROJECTID
     *
     * @param projectid the value for ku8_proj_rc_inst.PROJECTID
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.PROJECT_INSTANCE_ID
     *
     * @return the value of ku8_proj_rc_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    public Integer getProjectInstanceId() {
        return projectInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.PROJECT_INSTANCE_ID
     *
     * @param projectInstanceId the value for ku8_proj_rc_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    public void setProjectInstanceId(Integer projectInstanceId) {
        this.projectInstanceId = projectInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.PROJECT_SERVICE_ID
     *
     * @return the value of ku8_proj_rc_inst.PROJECT_SERVICE_ID
     *
     * @mbggenerated
     */
    public Integer getProjectServiceId() {
        return projectServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.PROJECT_SERVICE_ID
     *
     * @param projectServiceId the value for ku8_proj_rc_inst.PROJECT_SERVICE_ID
     *
     * @mbggenerated
     */
    public void setProjectServiceId(Integer projectServiceId) {
        this.projectServiceId = projectServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.TENANT_ID
     *
     * @return the value of ku8_proj_rc_inst.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.TENANT_ID
     *
     * @param tenantId the value for ku8_proj_rc_inst.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.ZONE_ID
     *
     * @return the value of ku8_proj_rc_inst.ZONE_ID
     *
     * @mbggenerated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.ZONE_ID
     *
     * @param zoneId the value for ku8_proj_rc_inst.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.NAMESPACE
     *
     * @return the value of ku8_proj_rc_inst.NAMESPACE
     *
     * @mbggenerated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.NAMESPACE
     *
     * @param namespace the value for ku8_proj_rc_inst.NAMESPACE
     *
     * @mbggenerated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.RC_NAME
     *
     * @return the value of ku8_proj_rc_inst.RC_NAME
     *
     * @mbggenerated
     */
    public String getRcName() {
        return rcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.RC_NAME
     *
     * @param rcName the value for ku8_proj_rc_inst.RC_NAME
     *
     * @mbggenerated
     */
    public void setRcName(String rcName) {
        this.rcName = rcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.POD_LABEL
     *
     * @return the value of ku8_proj_rc_inst.POD_LABEL
     *
     * @mbggenerated
     */
    public String getPodLabel() {
        return podLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.POD_LABEL
     *
     * @param podLabel the value for ku8_proj_rc_inst.POD_LABEL
     *
     * @mbggenerated
     */
    public void setPodLabel(String podLabel) {
        this.podLabel = podLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.NOTE
     *
     * @return the value of ku8_proj_rc_inst.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.NOTE
     *
     * @param note the value for ku8_proj_rc_inst.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_proj_rc_inst.LAST_UPDATED
     *
     * @return the value of ku8_proj_rc_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_proj_rc_inst.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_proj_rc_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}