package org.ku8eye.domain;

import java.util.Date;

public class Ku8ResPartion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.NAMESPACE
     *
     * @mbggenerated
     */
    private String namespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.ID
     *
     * @return the value of ku8_res_partion.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.ID
     *
     * @param id the value for ku8_res_partion.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.CLUSTER_ID
     *
     * @return the value of ku8_res_partion.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.CLUSTER_ID
     *
     * @param clusterId the value for ku8_res_partion.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.NAMESPACE
     *
     * @return the value of ku8_res_partion.NAMESPACE
     *
     * @mbggenerated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.NAMESPACE
     *
     * @param namespace the value for ku8_res_partion.NAMESPACE
     *
     * @mbggenerated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.NOTE
     *
     * @return the value of ku8_res_partion.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.NOTE
     *
     * @param note the value for ku8_res_partion.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.LAST_UPDATED
     *
     * @return the value of ku8_res_partion.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_res_partion.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}