package org.ku8eye.domain;

import java.util.Date;

public class Ku8ResPartion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.NAMESPACE
     *
     * @mbggenerated
     */
    private String namespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.POD_LIMIT
     *
     * @mbggenerated
     */
    private Integer podLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.CPU_LIMIT
     *
     * @mbggenerated
     */
    private Integer cpuLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.MEMORY_LIMIT
     *
     * @mbggenerated
     */
    private Integer memoryLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.RC_LIMIT
     *
     * @mbggenerated
     */
    private Integer rcLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.SERVICE_LIMIT
     *
     * @mbggenerated
     */
    private Integer serviceLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.PV_LIMIT
     *
     * @mbggenerated
     */
    private Integer pvLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_res_partion.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.ID
     *
     * @return the value of ku8_res_partion.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.ID
     *
     * @param id the value for ku8_res_partion.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.CLUSTER_ID
     *
     * @return the value of ku8_res_partion.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.CLUSTER_ID
     *
     * @param clusterId the value for ku8_res_partion.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.NAMESPACE
     *
     * @return the value of ku8_res_partion.NAMESPACE
     *
     * @mbggenerated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.NAMESPACE
     *
     * @param namespace the value for ku8_res_partion.NAMESPACE
     *
     * @mbggenerated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.POD_LIMIT
     *
     * @return the value of ku8_res_partion.POD_LIMIT
     *
     * @mbggenerated
     */
    public Integer getPodLimit() {
        return podLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.POD_LIMIT
     *
     * @param podLimit the value for ku8_res_partion.POD_LIMIT
     *
     * @mbggenerated
     */
    public void setPodLimit(Integer podLimit) {
        this.podLimit = podLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.CPU_LIMIT
     *
     * @return the value of ku8_res_partion.CPU_LIMIT
     *
     * @mbggenerated
     */
    public Integer getCpuLimit() {
        return cpuLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.CPU_LIMIT
     *
     * @param cpuLimit the value for ku8_res_partion.CPU_LIMIT
     *
     * @mbggenerated
     */
    public void setCpuLimit(Integer cpuLimit) {
        this.cpuLimit = cpuLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.MEMORY_LIMIT
     *
     * @return the value of ku8_res_partion.MEMORY_LIMIT
     *
     * @mbggenerated
     */
    public Integer getMemoryLimit() {
        return memoryLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.MEMORY_LIMIT
     *
     * @param memoryLimit the value for ku8_res_partion.MEMORY_LIMIT
     *
     * @mbggenerated
     */
    public void setMemoryLimit(Integer memoryLimit) {
        this.memoryLimit = memoryLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.RC_LIMIT
     *
     * @return the value of ku8_res_partion.RC_LIMIT
     *
     * @mbggenerated
     */
    public Integer getRcLimit() {
        return rcLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.RC_LIMIT
     *
     * @param rcLimit the value for ku8_res_partion.RC_LIMIT
     *
     * @mbggenerated
     */
    public void setRcLimit(Integer rcLimit) {
        this.rcLimit = rcLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.SERVICE_LIMIT
     *
     * @return the value of ku8_res_partion.SERVICE_LIMIT
     *
     * @mbggenerated
     */
    public Integer getServiceLimit() {
        return serviceLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.SERVICE_LIMIT
     *
     * @param serviceLimit the value for ku8_res_partion.SERVICE_LIMIT
     *
     * @mbggenerated
     */
    public void setServiceLimit(Integer serviceLimit) {
        this.serviceLimit = serviceLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.PV_LIMIT
     *
     * @return the value of ku8_res_partion.PV_LIMIT
     *
     * @mbggenerated
     */
    public Integer getPvLimit() {
        return pvLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.PV_LIMIT
     *
     * @param pvLimit the value for ku8_res_partion.PV_LIMIT
     *
     * @mbggenerated
     */
    public void setPvLimit(Integer pvLimit) {
        this.pvLimit = pvLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.NOTE
     *
     * @return the value of ku8_res_partion.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.NOTE
     *
     * @param note the value for ku8_res_partion.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_res_partion.LAST_UPDATED
     *
     * @return the value of ku8_res_partion.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_res_partion.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_res_partion.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}