package org.ku8eye.domain;

import java.util.Date;

public class Ku8sSrvEndpoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.NODE_ROLE
     *
     * @mbggenerated
     */
    private Byte nodeRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.SERVICE_TYPE
     *
     * @mbggenerated
     */
    private Byte serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.HOST_ID
     *
     * @mbggenerated
     */
    private Integer hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.SERVICE_URL
     *
     * @mbggenerated
     */
    private String serviceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.SERVICE_STATUS
     *
     * @mbggenerated
     */
    private Byte serviceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8s_srv_endpoint.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.ID
     *
     * @return the value of ku8s_srv_endpoint.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.ID
     *
     * @param id the value for ku8s_srv_endpoint.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.NODE_ROLE
     *
     * @return the value of ku8s_srv_endpoint.NODE_ROLE
     *
     * @mbggenerated
     */
    public Byte getNodeRole() {
        return nodeRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.NODE_ROLE
     *
     * @param nodeRole the value for ku8s_srv_endpoint.NODE_ROLE
     *
     * @mbggenerated
     */
    public void setNodeRole(Byte nodeRole) {
        this.nodeRole = nodeRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.SERVICE_TYPE
     *
     * @return the value of ku8s_srv_endpoint.SERVICE_TYPE
     *
     * @mbggenerated
     */
    public Byte getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.SERVICE_TYPE
     *
     * @param serviceType the value for ku8s_srv_endpoint.SERVICE_TYPE
     *
     * @mbggenerated
     */
    public void setServiceType(Byte serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.CLUSTER_ID
     *
     * @return the value of ku8s_srv_endpoint.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.CLUSTER_ID
     *
     * @param clusterId the value for ku8s_srv_endpoint.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.HOST_ID
     *
     * @return the value of ku8s_srv_endpoint.HOST_ID
     *
     * @mbggenerated
     */
    public Integer getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.HOST_ID
     *
     * @param hostId the value for ku8s_srv_endpoint.HOST_ID
     *
     * @mbggenerated
     */
    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.SERVICE_URL
     *
     * @return the value of ku8s_srv_endpoint.SERVICE_URL
     *
     * @mbggenerated
     */
    public String getServiceUrl() {
        return serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.SERVICE_URL
     *
     * @param serviceUrl the value for ku8s_srv_endpoint.SERVICE_URL
     *
     * @mbggenerated
     */
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.SERVICE_STATUS
     *
     * @return the value of ku8s_srv_endpoint.SERVICE_STATUS
     *
     * @mbggenerated
     */
    public Byte getServiceStatus() {
        return serviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.SERVICE_STATUS
     *
     * @param serviceStatus the value for ku8s_srv_endpoint.SERVICE_STATUS
     *
     * @mbggenerated
     */
    public void setServiceStatus(Byte serviceStatus) {
        this.serviceStatus = serviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.NOTE
     *
     * @return the value of ku8s_srv_endpoint.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.NOTE
     *
     * @param note the value for ku8s_srv_endpoint.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8s_srv_endpoint.LAST_UPDATED
     *
     * @return the value of ku8s_srv_endpoint.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8s_srv_endpoint.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8s_srv_endpoint.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}