package org.ku8eye.domain;

import java.util.Date;

public class Ku8ServiceTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.TENANT_ID
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.OWNER
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.ICON_URL
     *
     * @mbggenerated
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.K8S_VERSION
     *
     * @mbggenerated
     */
    private String k8sVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.ZONE_ID
     *
     * @mbggenerated
     */
    private Integer zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.JSON_SPEC
     *
     * @mbggenerated
     */
    private String jsonSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.PREV_JSON_SPEC
     *
     * @mbggenerated
     */
    private String prevJsonSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_service_template.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.ID
     *
     * @return the value of ku8_service_template.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.ID
     *
     * @param id the value for ku8_service_template.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.TENANT_ID
     *
     * @return the value of ku8_service_template.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.TENANT_ID
     *
     * @param tenantId the value for ku8_service_template.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.OWNER
     *
     * @return the value of ku8_service_template.OWNER
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.OWNER
     *
     * @param owner the value for ku8_service_template.OWNER
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.NAME
     *
     * @return the value of ku8_service_template.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.NAME
     *
     * @param name the value for ku8_service_template.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.ICON_URL
     *
     * @return the value of ku8_service_template.ICON_URL
     *
     * @mbggenerated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.ICON_URL
     *
     * @param iconUrl the value for ku8_service_template.ICON_URL
     *
     * @mbggenerated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.VERSION
     *
     * @return the value of ku8_service_template.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.VERSION
     *
     * @param version the value for ku8_service_template.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.K8S_VERSION
     *
     * @return the value of ku8_service_template.K8S_VERSION
     *
     * @mbggenerated
     */
    public String getK8sVersion() {
        return k8sVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.K8S_VERSION
     *
     * @param k8sVersion the value for ku8_service_template.K8S_VERSION
     *
     * @mbggenerated
     */
    public void setK8sVersion(String k8sVersion) {
        this.k8sVersion = k8sVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.ZONE_ID
     *
     * @return the value of ku8_service_template.ZONE_ID
     *
     * @mbggenerated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.ZONE_ID
     *
     * @param zoneId the value for ku8_service_template.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.CLUSTER_ID
     *
     * @return the value of ku8_service_template.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.CLUSTER_ID
     *
     * @param clusterId the value for ku8_service_template.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.JSON_SPEC
     *
     * @return the value of ku8_service_template.JSON_SPEC
     *
     * @mbggenerated
     */
    public String getJsonSpec() {
        return jsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.JSON_SPEC
     *
     * @param jsonSpec the value for ku8_service_template.JSON_SPEC
     *
     * @mbggenerated
     */
    public void setJsonSpec(String jsonSpec) {
        this.jsonSpec = jsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.PREV_JSON_SPEC
     *
     * @return the value of ku8_service_template.PREV_JSON_SPEC
     *
     * @mbggenerated
     */
    public String getPrevJsonSpec() {
        return prevJsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.PREV_JSON_SPEC
     *
     * @param prevJsonSpec the value for ku8_service_template.PREV_JSON_SPEC
     *
     * @mbggenerated
     */
    public void setPrevJsonSpec(String prevJsonSpec) {
        this.prevJsonSpec = prevJsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.NOTE
     *
     * @return the value of ku8_service_template.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.NOTE
     *
     * @param note the value for ku8_service_template.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_service_template.LAST_UPDATED
     *
     * @return the value of ku8_service_template.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_service_template.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_service_template.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}